use u937509157_omarb;

CREATE TABLE IF NOT EXISTS hintsTbl (
    ID INT NOT NULL AUTO_INCREMENT,
    Hint VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS locationTbl (
    ID INT NOT NULL AUTO_INCREMENT,
    zipCode INT NOT NULL,
    Address VARCHAR(45) NOT NULL,
    Country VARCHAR(25),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS playersTbl (
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    Age INT NOT NULL,
    firstName VARCHAR(25) NOT NULL,
    middleName VARCHAR(25),
    lastName VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hostTbl (
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    Age INT NOT NULL,
    firstName VARCHAR(25) NOT NULL,
    middleName VARCHAR(25),
    lastName VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

